name = "CozyTech SMP"
author = "Konkers"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40e741b9d8ca119fa6091b0a6d76d792e0a8d20d45308265736c5b268a6b7091"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
